name: BinderTutorial_QC
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.7
- matplotlib=2.2.3
- conda-forge::numpy=1.16.2
- pandas=0.24.2
- seaborn=0.9.0
- scikit-learn=0.20.3
- xlrd=1.2.0
